name: Tests
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - run: pip install crossplane

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
  
    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...
